DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

lms2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from lms2 import settings
from courses.views import *
from operations.views import *
from organizations.views import *
from users.views import *

urlpatterns = [
      path('admin/', admin.site.urls),
      # 首页
      path('', Index.as_view(), name='index'),
      # 用户：
      path('login/', LoginView.as_view(), name='login'),
      path('logout/', LogoutView.as_view(), name='logout'),
      path('register/', RegisterView.as_view(), name='register'),
      path('userEdit/', UserEditView.as_view(), name='userEdit'),
      path('TeacherEdit/', TeacherEditView.as_view(), name='teacherEdit'),
      path('changPWD/', ChangePasswordView.as_view(), name='CPW'),
      path('userFav/', UserFav.as_view(), name='userFav'),
      path('deleteFav/<int:fav_id>/', DeleteFav.as_view(), name='deleteFav'),
      path('userCourses/', UserCourses.as_view(), name='userCourses'),
      path('delete_course/<int:cid>/', Delete_course.as_view(), name='delete_course'),
      path('Message/', Message.as_view(), name='Message'),
      # 机构：
      path('OrgList/', OrganizationsView.as_view(), name='OrganizationsView'),
      path('OrgDetail/<int:org_id>/', OrgDetailView.as_view(), name='OrgDetail'),
      path('OrgDetail_home/<int:org_id>/', OrgDetail_home.as_view(), name='OrgDetail_home'),
      path('OrgDetail_desc/<int:org_id>/', OrgDetail_descView.as_view(), name='OrgDetail_desc'),
      path('OrgDetail_teacher/<int:org_id>/', OrgDetail_teacherView.as_view(), name='OrgDetail_teacher'),
      path('OrgDetail_course/<int:org_id>/', OrgDetail_courseView.as_view(), name='OrgDetail_course'),
      # 课程
      path('CourseList/', CourseView.as_view(), name='CourseList'),
      path('CourseDetail/<int:course_id>/', CourseDetailView.as_view(), name='CourseDetail'),
      path('CourseDetail_home/<int:course_id>/', CourseDetail_home.as_view(), name='CourseDetail_home'),
      path('CourseDetail_desc/<int:course_id>/', CourseDetail_descView.as_view(), name='CourseDetail_desc'),
      path('CourseDetail_teacher/<int:course_id>/', CourseDetail_teacherView.as_view(),
           name='CourseDetail_teacher'),
      path('CourseDetail_start/<int:course_id>/', CourseDetail_startView.as_view(),
           name='CourseDetail_start'),
      path('Course_learn/<int:tid>/', Course_learn.as_view(), name='Course_learn'),

      # 教师课程
      path('teacherZoom/', TeacherZoom.as_view(), name='teacherZoom'),
      path('teacherZoom/Course_edit/<int:course_id>/', Course_edit.as_view(), name='Course_edit'),
      path('teacherZoom/Course_edit/<int:course_id>/desc/', Course_edit_desc.as_view(),
           name='Course_edit_desc'),
      path('teacherZoom/Course_edit/<int:course_id>/home/', Course_edite_home.as_view(),
           name='Course_edite_home'),
      path('teacherZoom/Course_edit/<int:course_id>/add_notice/', Add_notice.as_view(),
           name='add_notice'),
      path('teacherZoom/Course_edit/<int:course_id>/add_lesson/', Add_lesson.as_view(),
           name='add_lesson'),
      path('teacherZoom/Lesson_edit/<int:lid>/', Lesson_edit.as_view(), name='Lesson_edit'),
      path('teacherZoom/Content_edit/<int:tid>/', Content_edit.as_view(), name='Content_edit'),
      # 操作
      path('Content_delete/<int:tid>/', Content_delete.as_view(), name='Content_delete'),
      path('delete_lesson/<int:lid>/', Delete_lesson.as_view(), name='delete_lesson'),
      path('undisplay_course/<int:cid>/', unDisplay_course.as_view(), name='undisplay_course'),
      path('display_course/<int:cid>/', display_course.as_view(), name='display_course'),
      path('score/<int:task_id>/', Score.as_view(), name='score'),

      path('fav_org/<int:oid>/', Fav_org.as_view(), name='fav_org'),
      path('fav_course/<int:cid>/', Fav_course.as_view(), name='fav_course'),

      path('readMessage/<int:nid>/', ReadMessage.as_view(), name='readMessage'),
      path('task/<int:tid>/', task.as_view(), name='task'),
      path('edittask/<int:tid>/', editTask.as_view(), name='editTask'),

      path('uploadfile/<int:tid>/', Uploadfile.as_view(), name='uploadfile'),
      path('postdetail/<int:cid>/', Post_detail.as_view(), name='pD'),


      path('_nested_admin/', include('nested_admin.urls')),
      path('ueditor/', include('DjangoUeditor.urls')),

  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from DjangoUeditor.models import UEditorField

from django.db import models

from users.models import BaseModel
from organizations.models import Teacher, CourseOrg


class Course(BaseModel):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name="讲师")
    org = models.ForeignKey(CourseOrg, null=True, blank=True, on_delete=models.CASCADE, verbose_name="课程机构")
    name = models.CharField(verbose_name="课程名", max_length=50)
    desc = models.CharField(verbose_name="课程描述", max_length=300, null=True, blank=True)
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    click_nums = models.IntegerField(default=0, verbose_name="点击数")
    category = models.CharField(default=u"后端开发", max_length=20, verbose_name="课程类别")
    tag = models.CharField(default="", verbose_name="课程标签", max_length=10, null=True, blank=True)
    youneed_know = models.CharField(default="", max_length=300, verbose_name="课程须知", null=True, blank=True)
    detail = UEditorField(verbose_name="课程详情", default='', blank=True, imagePath='course_detail/', toolbars="full",
                          filePath="course_detail_files/", )
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name="封面图", max_length=100)
    is_banner = models.BooleanField(default=False, verbose_name="是否宣传")

    class Meta:
        verbose_name = "课程信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def lesson_nums(self):
        return self.lesson_set.all().count()

    def show_image(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<img src='{}'>".format(self.image.url))

    show_image.short_description = "图片"

    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='/course/{}'>跳转</a>".format(self.id))

    go_to.short_description = "跳转"


class Notice(BaseModel):
    title = models.CharField(verbose_name="通知标题", max_length=100)
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE, null=True)
    content = UEditorField(verbose_name="课程详情", default='', blank=True, imagePath='course_notice', toolbars="mini",
                           filePath="course_notice_files/", )
    class Meta:
        verbose_name = "课程通知"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class BannerCourse(Course):
    class Meta:
        verbose_name = "轮播课程"
        verbose_name_plural = verbose_name
        proxy = True


class CourseTag(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    tag = models.CharField(max_length=100, verbose_name="标签")

    class Meta:
        verbose_name = "课程标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    name = models.CharField(max_length=100, verbose_name="章节名")
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")

    class Meta:
        verbose_name = "课程章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Content(BaseModel):
    lesson = models.ForeignKey(Lesson, verbose_name="课程章节", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"小节名称", null=True)
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    learning_space = UEditorField(verbose_name="学习空间", default='', blank=True, imagePath='course_content/',
                                  toolbars="full", filePath="course_content_files/", )
    file = models.FileField(upload_to="course/resourse/%Y/%m", verbose_name="课件资料", max_length=200, null=True,
                            blank=True)

    class Meta:
        verbose_name = "课程小节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(BaseModel):
    content = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="内容", default='')
    name = models.CharField(max_length=100, verbose_name=u"名称")
    file = models.FileField(upload_to="course/resourse/%Y/%m", verbose_name="下载地址", max_length=200, null=True,
                            blank=True)

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

operations/models.py
from datetime import datetime

from django.db import models
from DjangoUeditor.models import UEditorField
from django.contrib.auth import get_user_model

from users.models import BaseModel
from courses.models import Course, Lesson, Content, Notice

UserProfile = get_user_model()


class Banner(BaseModel):
    title = models.CharField(max_length=100, verbose_name="标题")
    image = models.ImageField(upload_to="banner/%Y/%m", max_length=200, verbose_name="轮播图")
    url = models.URLField(max_length=200, verbose_name="访问地址")
    index = models.IntegerField(default=0, verbose_name="顺序")

    class Meta:
        verbose_name = "轮播图"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class UserAsk(BaseModel):
    name = models.CharField(max_length=20, verbose_name="姓名")
    mobile = models.CharField(max_length=11, verbose_name="手机")
    course_name = models.CharField(max_length=50, verbose_name="课程名")

    class Meta:
        verbose_name = "用户咨询"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{name}_{course}({mobile})".format(name=self.name, course=self.course_name, mobile=self.mobile)


class CourseComments(BaseModel):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="用户")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    comments = models.CharField(max_length=200, verbose_name="评论内容")

    class Meta:
        verbose_name = "课程评论"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.comments


class UserFavorite(BaseModel):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="用户")
    fav_id = models.IntegerField(verbose_name="数据id")
    fav_type = models.IntegerField(choices=((2, "课程"), (1, "课程机构"), (3, "讲师")), default=1,verbose_name="收藏类型")

    class Meta:
        verbose_name = "用户收藏"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{user}_{id}".format(user=self.user.username, id=self.fav_id)


class UserMessage(BaseModel):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="用户")
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE, verbose_name="来自的通知",default=None)
    has_read = models.BooleanField(default=False, verbose_name="是否已读")

    class Meta:
        verbose_name = "用户消息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.message


class UserCourse(BaseModel):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="用户")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")

    class Meta:
        verbose_name = "用户课程"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course.name


class Task(BaseModel):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="学生", blank=True, null=True)
    content = models.ForeignKey(Content, on_delete=models.CASCADE, verbose_name="所属章节", blank=True, null=True)
    detail = UEditorField(verbose_name="课程编辑", default='', blank=True, imagePath='task/img/',
                          toolbars="full", filePath='task/file/')

    class Meta:
        verbose_name = "作业"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.content) + '作业'

templates/compose/teach/add-content-form.html
<button type="button"
        class="btn btn-success btn-lg"
        data-toggle="modal" data-target="#add_contentModal">
    Create A Content
</button>


<div class="modal fade" id="add_contentModal" tabindex="-1" role="dialog" aria-labelledby="add_contentModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="add_contentModalLabel">Are you sure?</h4>
            </div>
            <form method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    {% csrf_token %}
                    {{ form }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary"> Create</button>
                </div>
            </form>

        </div>
    </div>
</div>

templates/compose/teach/add-course-form.html
<!-- 弹出框触发按钮 -->
<button class="btn btn-primary" type="button" data-toggle="modal" data-target="#myModal">
    Create A New Course
</button>

<!-- 弹出框 -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Create A New Course</h4>
            </div>
            <div class="modal-body">
                <form id="myForm" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button id="submit" type="submit" class="btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#myForm').on('submit', function (event) {
            event.preventDefault(); // 阻止默认的表单提交行为
            // 获取表单数据
            var formData = $(this).serialize();
            // 发送 AJAX 请求
            $.ajax({
                url: $(this).attr('action'),
                method: $(this).attr('method'),
                data: formData,
                success: function (response) {
                    // 隐藏模态框
                    $('#myModal').modal('hide');
                    // 刷新原来的页面
                    window.location.reload();
                },
                error: function (xhr, status, error) {
                }
            });
        });
    });
</script>

templates/compose/teach/add-lesson-form.html
<button type="button"
        class="btn btn-success btn-lg"
        data-toggle="modal" data-target="#ADLF">
    Create A New Lesson
</button>


<div class="modal fade" id="ADLF" tabindex="-1" role="dialog"
     aria-labelledby="taskgradeModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="taskgradeModalLabel">Input the score od task</h4>
            </div>
            <form method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    {{ lesson_form }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>

        </div>
    </div>
</div>

templates/compose/teach/content-edite-list.html
<div>
    <h3>{{ lesson.name }}</h3>
    <table class="table-hover">
        <tr class="title-tr">
            <td style="width: 10px">Index</td>
            <td style="width: 50px">Content Name</td>
            <td style="width: 20px">File</td>
            <td style="width: 30px">Size Of Content</td>
            <td style="width: 30px">Number Of Tasks</td>
            <td style="width: 50px">Operate</td>
        </tr>
        {% for content in contents %}
            <tr>
                <th><h4>{{ forloop.counter }}</h4></th>
                <th><h3>{{ content.name }}</h3></th>
                <th><h4>
                    {% if content.file %}
                        <a href="{{ content.file.url }}">Download File</a>
                    {% else %}
                        <span style="color: #c12e2a">Empty</span>
                    {% endif %}
                </h4>
                </th>
                <th><h4>{{ content.learning_space|length }}</h4></th>
                <th><h4>{{ content.task_set.count }}</h4></th>
                <th>
                    <a type="button" class="btn btn-primary" href="{% url 'Content_edit' content.id %}">Edite</a>
{#                    <a type="button" class="btn btn-danger" href="{% url 'Content_delete' content.id %}">Delete</a>#}
                    {% include 'compose/common/delete.html' with url='Content_delete' id=content.id %}
                </th>
            </tr>
        {% endfor %}
    </table>
</div>

<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 8px;
        border-bottom: 1px solid #ddd;
    }

    td {
        font-size: 20px;
    }
</style>

templates/compose/teach/content-show.html
{% if data == 1 %}

    <button class="btn btn-warning btn-lg" id="showContent">Show</button>

{% else %}
    <div id="ContentShow" style="display: block;margin-left: 100px;margin-top: 20px">
        {{ content.learning_space|safe }}
    </div>
    <script>
        document.getElementById('showContent').addEventListener('click', function () {

            {% if data1 != 1 %}
                document.getElementById('showTaskList').style.display = 'none';
                document.getElementById('formContent').style.display = 'none';
            {% endif %}
            document.getElementById('ContentShow').style.display = 'block';
            document.getElementById('TSK').style.display = 'none';
        });
    </script>


{% endif %}

templates/compose/teach/course-detail-show.html
{% if data == 1 %}

<button class="btn btn-primary btn-lg" id="CDetailS">Show the detail</button>

{% else %}
<div id="ShowD" style="display: block;margin-left: 100px">
    {% include 'compose/common/introduction.html' with data=course.detail %}
</div>


<script>
    document.getElementById('CDetailS').addEventListener('click', function () {
        document.getElementById('form').style.display = 'none';
        document.getElementById('ShowD').style.display = 'block';
    });
</script>

{% endif %}

templates/compose/teach/course-list.html
<table class="table-hover">
    <tr class="title-tr">
        <td style="width: 20%">Course Cover</td>
        <td style="width: 10%">Course title</td>
        <td style="width: 50px">Course category</td>
        <td style="width: 20px">Number of students</td>
        <td style="width: 20px">Number of clicked</td>
        <td style="width: 20px">Number of collections</td>
        <td style="width: 50px">Status</td>
        <td style="width: 50px">Operate</td>
    </tr>
    {% for course in courses %}
        <tr>
            <th>
                <img src="{{ MEDIA_URL }}{{ course.image }}">
            </th>
            <th>{{ course.name }}</th>
            <th>{{ course.category }}</th>
            <th>{{ course.students }}</th>
            <th>{{ course.click_nums}}</th>
            <th>{{ course.fav_nums }}</th>
            {% if course.status %}
                <th style="color: #09e809">displayed</th>
            {% else %}
                <th style="color: #ee1208">hidden</th>
            {% endif %}
            <th>
                {% include 'compose/teach/button-status.html' %}
                <a type="button" class="btn btn-primary btn-lg" href="{% url 'Course_edit' course.id %}">Open up</a>
            </th>
        </tr>
    {% endfor %}
</table>



<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    .title-tr {
        background-color: #eee9e9;
    }

    img {
        width: 150px;
        height: 100px;

        object-fit: cover; /* 设置图片填充方式为 cover */
    }

    {#    .imgtr {#}
    {#    margin: 5px 50px;#}
    {#    width: 50px;#}
    {#    height: 50px;#}
    {#    box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.2);#}
    {#    border-radius: 15px;#}
    {##}
    {
    #}#}
</style>

templates/compose/teach/course-nav.html
    <div class="nav4">
        <ul>
            <!-- 这里直接引用课程详情的home -->
            <li><a href="{% url 'Course_edite_home' course_id %}">
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;课程首页
            </a></li>
            <li><a href="{% url 'Course_edit_desc' course_id %}">
                <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>&nbsp;基本信息
            </a></li>
            <li><a href="{% url 'add_notice' course_id %}">
                <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;通知
            </a></li>
            <li><a href="{% url 'add_lesson' course_id %}">
                <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp;章节
            </a></li>

        </ul>
    </div>

templates/compose/teach/lesson-list.html
    {% for lesson in lesson_list %}
        <div class="chapter-list">
            <div class="lessonTitle">
                <a href="{% url 'Lesson_edit' lesson.id %}">
                    <h3><span class="glyphicon glyphicon-tasks" aria-hidden="true"
                              style="vertical-align: middle; margin-right: 1px;"></span>{{ lesson.name }}</h3>
                </a>

            </div>

            <div>
                {% for content in lesson.content_set.all %}
                    <a href="{% url 'Content_edit' content.id %}">
                        <div>
                            <h4><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                {{ content.name }}
                            </h4>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

templates/compose/teach/notice-form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <strong>标题：</strong>{{ form.title }}
        <button type="submit" class="btn btn-primary">提交</button>
    </div>
    <div>
        {{ form.media }}
        {{ form.content }}
    </div>
</form>

templates/compose/teach/task-grade-form.html
<button type="button"
        class="btn btn-success"
        data-toggle="modal" data-target="#taskgradeModal{{ task.id }}">
    Score
</button>


<div class="modal fade" id="taskgradeModal{{ task.id }}" tabindex="-1" role="dialog"
     aria-labelledby="taskgradeModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="taskgradeModalLabel">Input the score od task</h4>
            </div>
            <form action="{% url 'score' task.id %}" method="get">
                <div class="modal-body">
                    {% csrf_token %}
                    <input type="number" name="score" value="{{ score }}">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Score</button>
                </div>
            </form>

        </div>
    </div>
</div>

templates/compose/teach/teacher-form.html
<button class="btn btn-warning" type="button" data-toggle="modal" data-target="#teachFormModal">
    Update Your Information
</button>

<!-- 弹出框 -->
<div class="modal fade" id="teachFormModal" tabindex="-1" role="dialog" aria-labelledby="teachFormModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="teachFormModal">Update Your Information</h4>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'teacherEdit' %}">
                    {% csrf_token %}
                    {{ formTeacher }}
                    <button id="submit" type="submit" class="btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/compose/teach/teacher-modal.html
{% if data == 1 %}

    <a data-toggle="modal" data-target="#teacher_Modal">
        <span class="glyphicon glyphicon-education" aria-hidden="true"></span>My Information
    </a>


{% else %}

    <!-- Modal -->
    <div class="modal fade" id="teacher_Modal" tabindex="-1" role="dialog" aria-labelledby="statusModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="statusModalLabel">Hide this course</h4>
                </div>
                <div class="modal-body">
                    {% include 'compose/course/teacher-detail.html' with teacher=user.teacher %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


{% endif %}

templates/compose/teach/uploadfile.html
<button type="button" class="btn btn-success btn-lg"
        data-toggle="modal" data-target="#uploadModal"
        data-whatever="@mdo">
    Upload Files
</button>

<div class="modal fade" id="uploadModal" tabindex="-1" aria-labelledby="uploadModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="uploadModalLabel">上传课件</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form action="{% url 'uploadfile' content.id %}" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    {% csrf_token %}
                    {{ file_form }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btn-lg">upload</button>
                </div>
            </form>
        </div>
    </div>
</div>