DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

lms2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from lms2 import settings
from courses.views import *
from operations.views import *
from organizations.views import *
from users.views import *

urlpatterns = [
      path('admin/', admin.site.urls),
      # 首页
      path('', Index.as_view(), name='index'),
      # 用户：
      path('login/', LoginView.as_view(), name='login'),
      path('logout/', LogoutView.as_view(), name='logout'),
      path('register/', RegisterView.as_view(), name='register'),
      path('userEdit/', UserEditView.as_view(), name='userEdit'),
      path('TeacherEdit/', TeacherEditView.as_view(), name='teacherEdit'),
      path('changPWD/', ChangePasswordView.as_view(), name='CPW'),
      path('userFav/', UserFav.as_view(), name='userFav'),
      path('deleteFav/<int:fav_id>/', DeleteFav.as_view(), name='deleteFav'),
      path('userCourses/', UserCourses.as_view(), name='userCourses'),
      path('delete_course/<int:cid>/', Delete_course.as_view(), name='delete_course'),
      path('Message/', Message.as_view(), name='Message'),
      # 机构：
      path('OrgList/', OrganizationsView.as_view(), name='OrganizationsView'),
      path('OrgDetail/<int:org_id>/', OrgDetailView.as_view(), name='OrgDetail'),
      path('OrgDetail_home/<int:org_id>/', OrgDetail_home.as_view(), name='OrgDetail_home'),
      path('OrgDetail_desc/<int:org_id>/', OrgDetail_descView.as_view(), name='OrgDetail_desc'),
      path('OrgDetail_teacher/<int:org_id>/', OrgDetail_teacherView.as_view(), name='OrgDetail_teacher'),
      path('OrgDetail_course/<int:org_id>/', OrgDetail_courseView.as_view(), name='OrgDetail_course'),
      # 课程
      path('CourseList/', CourseView.as_view(), name='CourseList'),
      path('CourseDetail/<int:course_id>/', CourseDetailView.as_view(), name='CourseDetail'),
      path('CourseDetail_home/<int:course_id>/', CourseDetail_home.as_view(), name='CourseDetail_home'),
      path('CourseDetail_desc/<int:course_id>/', CourseDetail_descView.as_view(), name='CourseDetail_desc'),
      path('CourseDetail_teacher/<int:course_id>/', CourseDetail_teacherView.as_view(),
           name='CourseDetail_teacher'),
      path('CourseDetail_start/<int:course_id>/', CourseDetail_startView.as_view(),
           name='CourseDetail_start'),
      path('Course_learn/<int:tid>/', Course_learn.as_view(), name='Course_learn'),

      # 教师课程
      path('teacherZoom/', TeacherZoom.as_view(), name='teacherZoom'),
      path('teacherZoom/Course_edit/<int:course_id>/', Course_edit.as_view(), name='Course_edit'),
      path('teacherZoom/Course_edit/<int:course_id>/desc/', Course_edit_desc.as_view(),
           name='Course_edit_desc'),
      path('teacherZoom/Course_edit/<int:course_id>/home/', Course_edite_home.as_view(),
           name='Course_edite_home'),
      path('teacherZoom/Course_edit/<int:course_id>/add_notice/', Add_notice.as_view(),
           name='add_notice'),
      path('teacherZoom/Course_edit/<int:course_id>/add_lesson/', Add_lesson.as_view(),
           name='add_lesson'),
      path('teacherZoom/Lesson_edit/<int:lid>/', Lesson_edit.as_view(), name='Lesson_edit'),
      path('teacherZoom/Content_edit/<int:tid>/', Content_edit.as_view(), name='Content_edit'),
      # 操作
      path('Content_delete/<int:tid>/', Content_delete.as_view(), name='Content_delete'),
      path('delete_lesson/<int:lid>/', Delete_lesson.as_view(), name='delete_lesson'),
      path('undisplay_course/<int:cid>/', unDisplay_course.as_view(), name='undisplay_course'),
      path('display_course/<int:cid>/', display_course.as_view(), name='display_course'),
      path('score/<int:task_id>/', Score.as_view(), name='score'),

      path('fav_org/<int:oid>/', Fav_org.as_view(), name='fav_org'),
      path('fav_course/<int:cid>/', Fav_course.as_view(), name='fav_course'),

      path('readMessage/<int:nid>/', ReadMessage.as_view(), name='readMessage'),
      path('task/<int:tid>/', task.as_view(), name='task'),
      path('edittask/<int:tid>/', editTask.as_view(), name='editTask'),

      path('uploadfile/<int:tid>/', Uploadfile.as_view(), name='uploadfile'),
      path('postdetail/<int:cid>/', Post_detail.as_view(), name='pD'),


      path('_nested_admin/', include('nested_admin.urls')),
      path('ueditor/', include('DjangoUeditor.urls')),

  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizations/models.py
from django.db import models

from DjangoUeditor.models import UEditorField

from users.models import BaseModel


class City(BaseModel):
    name = models.CharField(max_length=20, verbose_name=u"城市名")
    desc = models.CharField(max_length=200, verbose_name=u"描述")

    class Meta:
        verbose_name = "城市"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseOrg(BaseModel):
    name = models.CharField(max_length=50, verbose_name="机构名称")
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="所在城市")
    desc = UEditorField(verbose_name='描述', default='', blank=True, imagePath='org_desc/', toolbars="full",
                        filePath="org_desc_files/", )
    tag = models.CharField(default="全国知名", max_length=10, verbose_name="机构标签")
    category = models.CharField(default="pxjg", verbose_name="机构类别", max_length=4,
                                choices=(("pxjg", "培训机构"), ("gr", "个人"), ("gx", "高校")))
    click_nums = models.IntegerField(default=0, verbose_name="点击数")
    fav_nums = models.IntegerField(default=0, verbose_name="收藏数")
    image = models.ImageField(upload_to="org/%Y/%m", verbose_name="logo", max_length=100)
    address = models.CharField(max_length=150, verbose_name="机构地址")
    students = models.IntegerField(default=0, verbose_name="学习人数")
    course_nums = models.IntegerField(default=0, verbose_name="课程数")
    is_auth = models.BooleanField(default=False, verbose_name="是否认证")
    is_gold = models.BooleanField(default=False, verbose_name="是否金牌")

    # def courses(self):
    #     courses = self.course_set.filter(is_classics=True)[:3]
    #     return courses

    class Meta:
        verbose_name = "课程机构"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


from users.models import UserProfile


class Teacher(BaseModel):
    user = models.OneToOneField(UserProfile, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="用户")
    org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name="所属机构")
    name = models.CharField(max_length=50, verbose_name=u"教师名")
    work_years = models.IntegerField(default=0, verbose_name="工作年限")
    work_company = models.CharField(max_length=50, verbose_name="就职公司")
    work_position = models.CharField(max_length=50, verbose_name="公司职位")
    points = models.CharField(max_length=50, verbose_name="教学特点")
    age = models.IntegerField(default=18, verbose_name="年龄")
    image = models.ImageField(upload_to="teacher/%Y/%m", verbose_name="头像", max_length=100)

    class Meta:
        verbose_name = "教师"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def course_nums(self):
        return self.course_set.all().count()

templates/compose/org/card.html
  <div class="ListCard">
        {% for org in orgs %}
            <div>
                <a href="{% url 'OrgDetail' org.id %}">
                    <img src="{{ MEDIA_URL }}{{ org.image }}" class="card-img-top" alt="机构封面图片">
                </a>
                <section>
                    <a href="{% url 'OrgDetail' org.id %}">
                        <h3 class="card-title">{{ org.name }}</h3>
                    </a>
                    <h4 class="card-text">地区：<strong>{{ org.city }}</strong></h4>
                    <h4 class="card-text">学习人数：<strong>{{ org.students }}</strong></h4>
                    <h4 class="card-text">课程数：<strong>{{ org.course_num }}</strong></h4>
                </section>

            </div>
        {% endfor %}
    </div>

templates/compose/org/org-base-detail.html
  <!-- 机构基本信息-->
    <div class="Detail">
        <div class="Img">
            <img src="{{ MEDIA_URL }}{{ org.image }}" alt="机构封面">
        </div>
        <div>
            <div class="nameH50">
                <h3>{{ org.name }}</h3>
            </div>

            <div class="H150">
                <div>
                    <h4>城市:<strong>{{ org.city }}</strong></h4>
                    <h4>机构类别:<strong>{{ org.category.name }}</strong></h4>
                    <h4>机构标签:<strong>{{ org.tag }}</strong></h4>
                    <h4>机构地址:<strong>{{ org.address }}</strong></h4>
                </div>
                <div>
                    <h4>课程数:<strong>{{ org.course_num }}</strong></h4>
                    <h4>收藏数:<strong>{{ org.fav_nums }}</strong></h4>
                    <h4>学习人数:<strong>{{ org.students }}</strong></h4>
                </div>
            </div>
        </div>
    </div>

templates/compose/org/org-base-nav.html
<!-- 导航-->
<div class="nav4">
    <ul>
        <li><a href="{% url 'OrgDetail_home' org_id %} ">
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;机构首页
        </a></li>
        <li><a href="{% url 'OrgDetail_desc' org_id %}">
            <span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span>&nbsp;机构介绍
        </a></li>
        <li><a href="{% url 'OrgDetail_course' org_id %}">
            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;机构课程
        </a></li>
        <li><a href="{% url 'OrgDetail_teacher' org_id %}">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;机构教师
        </a></li>
        {% include 'compose/common/fav.html' with data=1 id=org.id %}
    </ul>
</div>

templates/compose/org/org-course-list.html
<div>
    <h2>机构课程</h2>
</div>

        <div class="ListCard">
            {% for course in org_course_set_all %}
                <div>
                    <a href="{% url 'CourseDetail' course.id %}">
                        <img src="{{ MEDIA_URL }}{{ course.image }}" class="card-img-top" alt="课程封面图片">

                        <section>
                            <h3>{{ course.name }}</h3>
                            <h4>机构：<strong>{{ course.org }}</strong></h4>
                            <h4>教师：<strong>{{ course.teacher }}</strong></h4>
                            <h4>课程描述：<strong>{{ course.desc }}</strong></h4>

                        </section>
                    </a>
                </div>
            {% endfor %}
        </div>

templates/compose/org/org-teacher-list.html
<div><h2>机构教师</h2></div>

<div class="ListCard">
    {% for teacher in org.teacher_set.all %}
        {% include 'compose/course/teacher-detail.html' with teacher=teacher %}
    {% endfor %}
</div>