DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

lms2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from lms2 import settings
from courses.views import *
from operations.views import *
from organizations.views import *
from users.views import *

urlpatterns = [
      path('admin/', admin.site.urls),
      # 首页
      path('', Index.as_view(), name='index'),
      # 用户：
      path('login/', LoginView.as_view(), name='login'),
      path('logout/', LogoutView.as_view(), name='logout'),
      path('register/', RegisterView.as_view(), name='register'),
      path('userEdit/', UserEditView.as_view(), name='userEdit'),
      path('TeacherEdit/', TeacherEditView.as_view(), name='teacherEdit'),
      path('changPWD/', ChangePasswordView.as_view(), name='CPW'),
      path('userFav/', UserFav.as_view(), name='userFav'),
      path('deleteFav/<int:fav_id>/', DeleteFav.as_view(), name='deleteFav'),
      path('userCourses/', UserCourses.as_view(), name='userCourses'),
      path('delete_course/<int:cid>/', Delete_course.as_view(), name='delete_course'),
      path('Message/', Message.as_view(), name='Message'),
      # 机构：
      path('OrgList/', OrganizationsView.as_view(), name='OrganizationsView'),
      path('OrgDetail/<int:org_id>/', OrgDetailView.as_view(), name='OrgDetail'),
      path('OrgDetail_home/<int:org_id>/', OrgDetail_home.as_view(), name='OrgDetail_home'),
      path('OrgDetail_desc/<int:org_id>/', OrgDetail_descView.as_view(), name='OrgDetail_desc'),
      path('OrgDetail_teacher/<int:org_id>/', OrgDetail_teacherView.as_view(), name='OrgDetail_teacher'),
      path('OrgDetail_course/<int:org_id>/', OrgDetail_courseView.as_view(), name='OrgDetail_course'),
      # 课程
      path('CourseList/', CourseView.as_view(), name='CourseList'),
      path('CourseDetail/<int:course_id>/', CourseDetailView.as_view(), name='CourseDetail'),
      path('CourseDetail_home/<int:course_id>/', CourseDetail_home.as_view(), name='CourseDetail_home'),
      path('CourseDetail_desc/<int:course_id>/', CourseDetail_descView.as_view(), name='CourseDetail_desc'),
      path('CourseDetail_teacher/<int:course_id>/', CourseDetail_teacherView.as_view(),
           name='CourseDetail_teacher'),
      path('CourseDetail_start/<int:course_id>/', CourseDetail_startView.as_view(),
           name='CourseDetail_start'),
      path('Course_learn/<int:tid>/', Course_learn.as_view(), name='Course_learn'),

      # 教师课程
      path('teacherZoom/', TeacherZoom.as_view(), name='teacherZoom'),
      path('teacherZoom/Course_edit/<int:course_id>/', Course_edit.as_view(), name='Course_edit'),
      path('teacherZoom/Course_edit/<int:course_id>/desc/', Course_edit_desc.as_view(),
           name='Course_edit_desc'),
      path('teacherZoom/Course_edit/<int:course_id>/home/', Course_edite_home.as_view(),
           name='Course_edite_home'),
      path('teacherZoom/Course_edit/<int:course_id>/add_notice/', Add_notice.as_view(),
           name='add_notice'),
      path('teacherZoom/Course_edit/<int:course_id>/add_lesson/', Add_lesson.as_view(),
           name='add_lesson'),
      path('teacherZoom/Lesson_edit/<int:lid>/', Lesson_edit.as_view(), name='Lesson_edit'),
      path('teacherZoom/Content_edit/<int:tid>/', Content_edit.as_view(), name='Content_edit'),
      # 操作
      path('Content_delete/<int:tid>/', Content_delete.as_view(), name='Content_delete'),
      path('delete_lesson/<int:lid>/', Delete_lesson.as_view(), name='delete_lesson'),
      path('undisplay_course/<int:cid>/', unDisplay_course.as_view(), name='undisplay_course'),
      path('display_course/<int:cid>/', display_course.as_view(), name='display_course'),
      path('score/<int:task_id>/', Score.as_view(), name='score'),

      path('fav_org/<int:oid>/', Fav_org.as_view(), name='fav_org'),
      path('fav_course/<int:cid>/', Fav_course.as_view(), name='fav_course'),

      path('readMessage/<int:nid>/', ReadMessage.as_view(), name='readMessage'),
      path('task/<int:tid>/', task.as_view(), name='task'),
      path('edittask/<int:tid>/', editTask.as_view(), name='editTask'),

      path('uploadfile/<int:tid>/', Uploadfile.as_view(), name='uploadfile'),
      path('postdetail/<int:cid>/', Post_detail.as_view(), name='pD'),


      path('_nested_admin/', include('nested_admin.urls')),
      path('ueditor/', include('DjangoUeditor.urls')),

  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from DjangoUeditor.models import UEditorField

from django.db import models

from users.models import BaseModel
from organizations.models import Teacher, CourseOrg


class Course(BaseModel):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name="讲师")
    org = models.ForeignKey(CourseOrg, null=True, blank=True, on_delete=models.CASCADE, verbose_name="课程机构")
    name = models.CharField(verbose_name="课程名", max_length=50)
    desc = models.CharField(verbose_name="课程描述", max_length=300, null=True, blank=True)
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    click_nums = models.IntegerField(default=0, verbose_name="点击数")
    category = models.CharField(default=u"后端开发", max_length=20, verbose_name="课程类别")
    tag = models.CharField(default="", verbose_name="课程标签", max_length=10, null=True, blank=True)
    youneed_know = models.CharField(default="", max_length=300, verbose_name="课程须知", null=True, blank=True)
    detail = UEditorField(verbose_name="课程详情", default='', blank=True, imagePath='course_detail/', toolbars="full",
                          filePath="course_detail_files/", )
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name="封面图", max_length=100)
    is_banner = models.BooleanField(default=False, verbose_name="是否宣传")

    class Meta:
        verbose_name = "课程信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def lesson_nums(self):
        return self.lesson_set.all().count()

    def show_image(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<img src='{}'>".format(self.image.url))

    show_image.short_description = "图片"

    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='/course/{}'>跳转</a>".format(self.id))

    go_to.short_description = "跳转"


class Notice(BaseModel):
    title = models.CharField(verbose_name="通知标题", max_length=100)
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE, null=True)
    content = UEditorField(verbose_name="课程详情", default='', blank=True, imagePath='course_notice', toolbars="mini",
                           filePath="course_notice_files/", )
    class Meta:
        verbose_name = "课程通知"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class BannerCourse(Course):
    class Meta:
        verbose_name = "轮播课程"
        verbose_name_plural = verbose_name
        proxy = True


class CourseTag(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    tag = models.CharField(max_length=100, verbose_name="标签")

    class Meta:
        verbose_name = "课程标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    name = models.CharField(max_length=100, verbose_name="章节名")
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")

    class Meta:
        verbose_name = "课程章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Content(BaseModel):
    lesson = models.ForeignKey(Lesson, verbose_name="课程章节", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"小节名称", null=True)
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    learning_space = UEditorField(verbose_name="学习空间", default='', blank=True, imagePath='course_content/',
                                  toolbars="full", filePath="course_content_files/", )
    file = models.FileField(upload_to="course/resourse/%Y/%m", verbose_name="课件资料", max_length=200, null=True,
                            blank=True)

    class Meta:
        verbose_name = "课程小节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(BaseModel):
    content = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="内容", default='')
    name = models.CharField(max_length=100, verbose_name=u"名称")
    file = models.FileField(upload_to="course/resourse/%Y/%m", verbose_name="下载地址", max_length=200, null=True,
                            blank=True)

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/Content_edit.html
{% extends 'compose/base/layout.html' %}
{% block title %}章节内容编辑{% endblock %}
{% block content %}

    {% include 'compose/common/back-to-url.html' with url='Lesson_edit' data=content.lesson.id lg=1 %}
    {% include 'compose/teach/content-edite-form.html' with data=1 %}
    {% include 'compose/teach/content-show.html' with data=1 %}
    {% include 'compose/teach/uploadfile.html' %}
    {% include 'compose/teach/task-list.html' with data=1 %}
    {% include 'compose/common/file.html'%}

    {% include 'compose/teach/content-edite-form.html' %}
    {% include 'compose/teach/content-show.html' %}
 {% include 'compose/teach/task-list.html' %}

{% endblock %}

templates/Course_edit.html
{% extends 'compose/base/layout.html' %}
{% block title %}课程界面{% endblock %}
{% block content %}


    <div class="bread">
        <ul>
            <li><a href="{% url 'index' %}">首页</a></li>
            <li><a href="{% url 'teacherZoom' %}">教师课程</a></li>
            <li><a href="{% url 'Course_edit' course_id %}">课程门户</a></li>
        </ul>
    {% include 'compose/common/back-to-url.html' with url='teacherZoom' %}
    </div>

    <!-- 信息-->
        {% include 'compose/course/course-base-detail.html' %}
        {% include 'compose/teach/course-nav.html' %}


    {% block branch %}
    {% endblock %}

{% endblock %}

templates/Course_edit_desc.html
{% extends "Course_edit.html" %}
{% block title %}{{ course.name }}详情{% endblock %}
{% block branch %}

    {% include 'compose/teach/course-desc-form.html' %}
    {% include 'compose/teach/course-detail-form.html' with data=1 %}
    {% include 'compose/teach/course-detail-show.html' with data=1 %}
    {% include 'compose/teach/course-detail-form.html' %}
    {% include 'compose/teach/course-detail-show.html' %}


{% endblock %}

templates/Lesson_edit.html
{% extends 'compose/base/layout.html' %}
{% block title %}内容列表{% endblock %}
{% block content %}
<div>
    {% include 'compose/common/back-to-url.html' with url='add_lesson' data=lesson.course.id lg=1 %}
    {% include 'compose/teach/add-content-form.html' %}
    {% include 'compose/common/delete.html' with url='delete_lesson' id=lesson.id data=1 %}
</div>
    <div style="overflow: auto;">
        {% include 'compose/teach/content-edite-list.html' %}
    </div>
{% endblock %}

templates/add_lesson.html
{% extends "Course_edit.html" %}
{% block title %}添加章节{% endblock %}
{% block branch %}

    <div>
        <div class="left-card">
            {% include 'compose/course/notice-list.html' %}
        </div>

        <div class="right-card">
            {% include 'compose/course/comment-list.html' %}
        </div>

        <div class="chapter-div">
            {% include 'compose/teach/add-lesson-form.html' %}
            {% include 'compose/teach/lesson-list.html' %}
        </div>

    </div>

{% endblock %}

templates/add_notice.html
{% extends "Course_edit.html" %}
{% block title %}添加通知{% endblock %}
{% block branch %}
    <div>
        <div class="right-card">
            {% include 'compose/course/notice-list.html' %}
        </div>
        <div style="margin-left: 50px">
            {% include 'compose/teach/notice-form.html' %}
        </div>
    </div>

{% endblock %}

templates/course-detail-desc.html
{% extends "course_detail_base.html" %}
{% block title %}{{ course.name }}详情{% endblock %}
{% block branch %}
{% include 'compose/common/introduction.html' with data=course.detail %}
{% endblock %}

templates/course-detail-homepage.html
{% extends "course_detail_base.html" %}
{% block title %}{{ course.name }}详情{% endblock %}
{% block branch %}

{% include 'compose/common/introduction.html' with data=course.detail %}
{% include 'compose/common/teacher-introduction.html'%}

    <h1>课程章节</h1>
    <div>

        <div class="left-card">
            {% include 'compose/course/notice-list.html' with notices=course.notice_set.all %}
        </div>

        <div class="right-card">
           {% include 'compose/course/comment-list.html' %}
        </div>

        <div class="chapter-div">
            {% if course.lesson_set.all %}
                {% include 'compose/course/lesson-list.html' with lesson_list=course.lesson_set.all %}
            {% else %}
                <p>暂无章节内容</p>
            {% endif %}
        </div>

    </div>

{% endblock %}

templates/course-detail-start.html
{% extends "course_detail_base.html" %}
{% block title %}{{ course.name }}门户{% endblock %}
{% block branch %}

    <div>
        <div class="left-card">
            {% include 'compose/course/notice-list.html' %}
        </div>

        <div class="right-card">
            {% include 'compose/course/comment-list.html' %}
        </div>

        <div class="chapter-div">
            {% include 'compose/course/lesson-list.html' %}
        </div>
    </div>
{% endblock %}

templates/course_list.html
{% extends 'compose/base/layout.html' %}

{% block title %}课程列表{% endblock %}

{% block content %}

    <div class="bread">
        <ul class="nav-list">
            <a href="{% url 'index' %}">首页</a>>
            <a href="{% url 'CourseList' %}">课程</a>
        </ul>
        {% include 'compose/common/back-to-url.html' with url='index' %}
    </div>

    <div style="margin-top: 10px">
        {% include 'compose/common/search.html' with data=1 %}
        {% include 'compose/common/category.html' %}
        {% include 'compose/common/sort.html' %}
    </div>
    {#课程列表#}
    {% include 'compose/course/card.html' %}

    <!-- 分页 -->
    {% include 'compose/common/pagination.html' with obj=courses %}


{% endblock %}

templates/index.html
{% extends 'compose/base/layout.html' %}

{% block title %}主页{% endblock %}

{% block content %}
    <div class="row" style="display: flex; justify-content: space-between;">
        <div style="width: 200px;">
            {% include 'compose/base/show.html' with title='Popular Organizations' link='OrgDetail' data=recommend_orgs %}
            {% include 'compose/base/show.html' with title='Popular Courses' link='CourseDetail' data=recommend_courses %}
        </div>
        <div class="mid-part" style="width: calc(100% - 500px);">
            {% include 'compose/base/banner.html' %}
        </div>
        <div style="width: 200px;">
                <p>You have studied {{ course_count }} courses</p>
                {% include 'compose/base/show.html' with title='My Courses' link='CourseDetail' data=my_courses name=1 %}
                <p>You have {{ fav_course_count }} favorite courses</p>
                {% include 'compose/base/show.html' with title='Favorite Courses' link='CourseDetail' data=my_fav_courses name=1 %}
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'compose/base/login_resister_view.html' %}
{% block title %}Sign in{% endblock %}

{% block form %}

    <div class="sign-form">
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label class="form-label">User Name</label>
                <input type="text" class="form-control" name="username" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" name="password">
            </div>
            {% if 错误 %}
                <strong class="errors">tips:{{ 错误 }}</strong>
            {% endif %}
            <div class="buttons">
                <button type="submit" class="btn btn-success btn-lg">Sign in</button>
                <a type="button" class="btn btn-warning btn-lg" href="{% url 'register' %}" style="margin-left: 30px">Sign up</a>
            </div>

        </form>
    </div>

    <style>
        .sign-form {
            margin-top: 100px;
            margin-right: 100px;
        }

        .mb-3 {
            margin-top: 20px;
        }

        .buttons {
            margin-top: 20px;
        }

        .form-label {
            font-size: 20px;
        }
        .errors {
        font-size: 20px;
            color: #c12e2a;
        }

    </style>


{% endblock %}

templates/teacher_zoom.html
{% extends 'compose/base/layout.html' %}
{% block title %}所授课程{% endblock %}
{% block content %}
<div style="margin: 15px 10px;">
    {% include 'compose/common/back-to-url.html' with url='index' %}
    {% include 'compose/teach/teacher-form.html' %}
    {% include 'compose/teach/add-course-form.html' %}
    <div style="margin-top: 10px">
        {% include 'compose/common/search.html' %}
        {% include 'compose/common/category.html' %}
        {% include 'compose/common/sort.html' %}
    </div>

    {% include 'compose/teach/course-list.html' with teacher=user.teacher %}
    {% include 'compose/common/pagination.html' with obj=courses %}
</div>
{# #}

{% endblock %}

templates/userFav.html
{% extends 'compose/base/layout.html' %}
{% block title %}我的课程{% endblock %}
{% block content %}
{% include 'compose/common/back-to-url.html' with url='index'%}

    <div><h1>收藏的机构</h1></div>
    {% include 'compose/user/userfav-org-list.html' %}

    <div><h1>收藏的课程</h1></div>
       {% include 'compose/user/userfav-course-list.html' %}

{% endblock %}